export const ROUTE_EXAMPLE_ENVIRONMENT_SELECTOR = "ROUTE_EXAMPLE_ENVIRONMENT_SELECTOR";
export const ROUTE_EXAMPLE_APP_START = "ROUTE_EXAMPLE_APP_START";
export const ROUTE_EXAMPLE_APP_BANK_ID_LOGIN = "ROUTE_EXAMPLE_APP_BANK_ID_LOGIN";
export const ROUTE_SKADEMELDING_START = "ROUTE_SKADEMELDING_START";
