export const REQUEST_SSO_TOKEN_FROM_API = "REQUEST_SSO_TOKEN_FROM_API";
export type REQUEST_SSO_TOKEN_FROM_API = typeof REQUEST_SSO_TOKEN_FROM_API;

export const REQUEST_SSO_TOKEN_FROM_ASYNC_STORAGE = "REQUEST_SSO_TOKEN_FROM_ASYNC_STORAGE";
export type REQUEST_SSO_TOKEN_FROM_ASYNC_STORAGE = typeof REQUEST_SSO_TOKEN_FROM_ASYNC_STORAGE;

export const RECEIVE_SSO_TOKEN = "RECEIVE_SSO_TOKEN";
export type RECEIVE_SSO_TOKEN = typeof RECEIVE_SSO_TOKEN;

export const FETCH_ERROR_SSO_TOKEN = "FETCH_ERROR_SSO_TOKEN";
export type FETCH_ERROR_SSO_TOKEN = typeof FETCH_ERROR_SSO_TOKEN;
